### ISSUE TITLE
How to differentiate a data model on basis of database 

### ISSUE THREAD

**Issue by Itachi3uchiha** [dymmond/mongoz#50]
Can anyone give me a solution for how to differentiate a data models on the basis of database. I am trying to access these database on the basis custom  parameters add in the meta class but it is not working?

**Comment by tarsil** [comment]
@Itachi3uchiha this is not an issue. Unfortunately what you want it is not clear to us.

Mongoz Meta class only accepts what it is mentioned there. Adding custom parameters like 

```python
class Meta:
    my_param = "whatever"
```

It is not possible. Unless you provide some more details of what you are trying to do, it will be hard to help you finding a solution for this.

**Comment by tarsil** [comment]
So if you say, "I have tow databases with the same definition of a Document, like a User", then you can simply use this https://mongoz.tarsild.io/queries/#using

**Comment by Itachi3uchiha** [comment]
Ok

**Comment by tarsil** [comment]
@Itachi3uchiha is this what you were looking for? https://mongoz.tarsild.io/queries/#using

**Comment by tarsil** [comment]
> No I'm not looking for this I want a model/documents differentiate on the basis of database?

@Itachi3uchiha please, provide an example, a concrete one preferentially. My understanding is that you want, for example:

1. Document `User` to be on a database `one`.
2. Document `Profile` to be on a database `two`.

Is this correct? If yes, then you can do like this:

```python
class User(mongoz.Document):
    ...
    class Meta:
        database = 'one'
```

```python
class Profile(mongoz.Document):
    ...
    class Meta:
        database = 'two'
```

All of this is in the documentation but if this is still not what you are looking for, then provide exactly an example as it is not clear.

**Comment by Itachi3uchiha** [comment]
Yes this exactly I'm looking for thank you

**Comment by tarsil** [comment]
@Itachi3uchiha no problem, this is also in the documentation of Mongoz. I'm closing this then 👍🏼

**Comment by Itachi3uchiha** [comment]
Yess

**Comment by tarsil** [comment]
@Itachi3uchiha we hope you enjoy Mongoz

**Comment by Itachi3uchiha** [comment]
Ya ofcourse
