### ISSUE TITLE
Add extra attribute in MetaInfo

### ISSUE THREAD

**Issue by Itachi3uchiha** [dymmond/mongoz#55]
Hiii, 
      I am working on a create_indexes directive but I'm getting a issue at the time of database type check. I want to add a extra db_types attribute in MetaInfo of mongoz and override the MetaInfo like this

 MetaInfo.slots = self.meta_class_info_slots

meta_class_info_slots: tuple = (

"pk",

"id_attribute",

"abstract",

"fields",

"registry",

"collection",

"indexes",

"parents"

"signals",

"database",

"manager",

"autogenerate_index",

"db_types"
)

But I'm encountering the issue at the time of access the db_types attribute in our meta class method. Do you know the alternative solution for this. How can I add db_types attribute then??

**Comment by Itachi3uchiha** [comment]
I'm using **document.meta.db_types** query for access these db_types attribute using meta class

**Comment by harshalizode** [comment]
Because that Meta of a Document does not allow you to do that.

> Hiii, I am working on a create_indexes directive but I'm getting a issue at the time of database type check. I want to add a extra db_types attribute in MetaInfo of mongoz and override the MetaInfo like this
> 
> MetaInfo.slots = self.meta_class_info_slots
> 
> meta_class_info_slots: tuple = (
> 
> "pk",
> 
> "id_attribute",
> 
> "abstract",
> 
> "fields",
> 
> "registry",
> 
> "collection",
> 
> "indexes",
> 
> "parents"
> 
> "signals",
> 
> "database",
> 
> "manager",
> 
> "autogenerate_index",
> 
> "db_types" )
> 
> But I'm encountering the issue at the time of access the db_types attribute in our meta class method. Do you know the alternative solution for this. How can I add db_types attribute then??

@Itachi3uchiha, because that Meta of a Document does not allow you to do that.

**Comment by tarsil** [comment]
At the moment it is not planned because of time but I'm more than happy to have a PR from you with a suggestion @Itachi3uchiha
